version: "3.1"
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./sql/medina.sql:/docker-entrypoint-initdb.d/medina.sql
volumes:
  mysql: